name: Sanity Test for main/dev  Branch

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

permissions:
  contents: write        # allow pushing/committing to repo
  pull-requests: write   # allow commenting on PRs




jobs:
  build-train-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Set up CML
        uses: iterative/setup-cml@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt
          pip install dvc[gcs]
          pip install pytest

      - name: Pull data from DVC remote
        run: |
          dvc pull -r gcs_remote

      - name: Train and evaluate model
        run: |
          python train.py

      - name: Run tests with pytest
        run: |
          pytest -s test.py 2>&1 | tee test_output.txt

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "# CI Report for Dev Branch" > report.md
          echo "##  Test Results" >> report.md
          echo "-----------------------------" >> report.md
          cat test_output.txt >> report.md
          echo "" >> report.md
          echo "##  Model Metrics" >> report.md
          echo "-----------------------------" >> report.md
          cat artifacts/metrics.csv >> report.md
          cml comment create --publish report.md
